version: '2.3'
services:  
  catalog:
    container_name: bacula_catalog
    image: popprrnp/bacula-catalog:latest
    environment: 
      MYSQL_ROOT_PASSWORD: root      
    volumes:
      - ./catalog/data:/var/lib/mysql  
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"    
    networks: 
      default:
    restart: always
  director:
    container_name: bacula_director
    image: geovanent/bacula-dir:v1
    tty: true
    ports:
      - 9103:9103
      - 1010:10000
    volumes:
      -  /Discos/:/Discos/
      - ./director/data:/etc/bacula/
      - ./director/wemin:/etc/webmin/
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
    networks:      
      default:    
    depends_on: 
      - catalog
    restart: always
  webacula:
    container_name: webacula
    image: popprrnp/web-bacula-gui:latest
    tty: true    
    ports:
      - 9002:80
    networks:      
      default:    
    depends_on: 
      - director
      - catalog
    restart: always
  bdashboard:
    container_name: bdashboard
    image: popprrnp/bacula-dashboard:latest
    tty: true  
    ports:
      - 9001:80  
    networks:      
      default:    
    depends_on: 
      - director
      - catalog
    restart: always
networks:  
  default:
